### ISSUE TITLE
Start API class to query the back-end

### ISSUE THREAD

**Issue by MaximilianV** [bptlab/rembrandt-frontend#2]
As the rembrandt front-end, I'd like to be able to retrieve information from the back-end, as well as posting new data to it.

---

### :question: Additional Questions to Answer / Consider

* Do we have separated API classes for resource organization and optimization, or is it one big interface?

---

## :white_check_mark: Conditions of satisfaction

- [x] The answer to separated APIs is documented.
- [x] The class(es) is(are) present, that connect(s) to the back-end.
- [x] At least one query/route is implemented and can be used as reference for adding new routes.

**Comment by friedow** [comment]
APIs should be implemented in a seperate classes located in `src/apis`.
